/// <reference types="node" />
import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';
import process from 'process';

const prisma = new PrismaClient();

async function main() {
  console.log('[SEED] Seeding database schema with Wikipedia Mumbai Suburban railway stations...');

  // Clear existing data safely
  await prisma.foodOrder.deleteMany();
  await prisma.foodItem.deleteMany();
  await prisma.foodVendor.deleteMany();
  await prisma.passenger.deleteMany();
  await prisma.booking.deleteMany();
  await prisma.delay.deleteMany();
  await prisma.trainRoute.deleteMany();
  await prisma.train.deleteMany();
  await prisma.station.deleteMany();
  await prisma.user.deleteMany();

  // --- USERS ---------------------------------------------------------------
  const hashedPassword = await bcrypt.hash('password123', 10);
  const adminPass = await bcrypt.hash('admin123', 10);

  await prisma.user.createMany({
    data: [
      { id: 'user-1', name: 'Rahul Sharma', email: 'rahul@example.com', phone: '9876543210', password: hashedPassword, role: 'user' },
      { id: 'user-2', name: 'Priya Patel', email: 'priya@example.com', phone: '9876543211', password: hashedPassword, role: 'user' },
      { id: 'admin-1', name: 'Admin User', email: 'admin@railway.com', phone: '9999999999', password: adminPass, role: 'admin' },
    ],
  });
  console.log('[SUCCESS] Users seeded');

  // --- STATIONS -----------------------------------------------------------
  const stations = [
    { id: 'st-ndls', code: 'NDLS', name: 'New Delhi', city: 'New Delhi', state: 'Delhi' },
    { id: 'st-mas', code: 'MAS', name: 'Chennai Central', city: 'Chennai', state: 'Tamil Nadu' },
    { id: 'st-hwh', code: 'HWH', name: 'Howrah Junction', city: 'Kolkata', state: 'West Bengal' },
    { id: 'st-sbc', code: 'SBC', name: 'KSR Bengaluru', city: 'Bengaluru', state: 'Karnataka' },
    { id: 'st-pune', code: 'PUNE', name: 'Pune Junction', city: 'Pune', state: 'Maharashtra' },
    { id: 'st-adi', code: 'ADI', name: 'Ahmedabad Junction', city: 'Ahmedabad', state: 'Gujarat' },
    { id: 'st-jp', code: 'JP', name: 'Jaipur Junction', city: 'Jaipur', state: 'Rajasthan' },
    { id: 'st-hyd', code: 'HYB', name: 'Hyderabad Deccan', city: 'Hyderabad', state: 'Telangana' },
    { id: 'st-bpl', code: 'BPL', name: 'Bhopal Junction', city: 'Bhopal', state: 'Madhya Pradesh' },
    { id: 'st-pnbe', code: 'PNBE', name: 'Patna Junction', city: 'Patna', state: 'Bihar' },
    { id: 'st-lko', code: 'LKO', name: 'Lucknow NR', city: 'Lucknow', state: 'UP' },
    { id: 'st-airl', code: 'AIRL', name: 'Airoli', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-amnl', code: 'AMNL', name: 'Aman Lodge', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-abh', code: 'ABH', name: 'Ambarnath', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-aby', code: 'ABY', name: 'Ambivli', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-adh', code: 'ADH', name: 'Andheri', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-apta', code: 'APTA', name: 'Apta', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-aso', code: 'ASO', name: 'Asangaon', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-atg', code: 'ATG', name: 'Atgaon', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-bud', code: 'BUD', name: 'Badlapur', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-bmnp', code: 'BMNP', name: 'Bamandongri', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-ba', code: 'BA', name: 'Bandra', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-bdts', code: 'BDTS', name: 'Bandra Terminus', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-bnd', code: 'BND', name: 'Bhandup', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-byr', code: 'BYR', name: 'Bhayandar', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-bipr', code: 'BIPR', name: 'Bhivpuri Road', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-bird', code: 'BIRD', name: 'Bhiwandi Road', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-bor', code: 'BOR', name: 'Boisar', city: 'Palghar', state: 'Maharashtra' },
    { id: 'st-brrd', code: 'BRRD', name: 'Bordi Road', city: 'Palghar', state: 'Maharashtra' },
    { id: 'st-bvi', code: 'BVI', name: 'Borivali', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-by', code: 'BY', name: 'Byculla', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-bepr', code: 'BEPR', name: 'CBD Belapur', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-cyr', code: 'CYR', name: 'Charni Road', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-cmbr', code: 'CMBR', name: 'Chembur', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-cstm', code: 'CSTM', name: 'Chhatrapati Shivaji Maharaj Terminus', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-ckhs', code: 'CKHS', name: 'Chikhale', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-ckli', code: 'CKLI', name: 'Chikhloli', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-chg', code: 'CHG', name: 'Chinchpokli', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-chok', code: 'CHOK', name: 'Chouk', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-chf', code: 'CHF', name: 'Chunabhatti', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-ccg', code: 'CCG', name: 'Churchgate', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-ctgn', code: 'CTGN', name: 'Cotton Green', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-crd', code: 'CRD', name: 'Currey Road', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-dr', code: 'DR', name: 'Dadar', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-drd', code: 'DRD', name: 'Dahanu Road', city: 'Palghar', state: 'Maharashtra' },
    { id: 'st-dic', code: 'DIC', name: 'Dahisar', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-dtvl', code: 'DTVL', name: 'Dativali', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-digh', code: 'DIGH', name: 'Digha Gaon', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-diva', code: 'DIVA', name: 'Diva Junction', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-dkrd', code: 'DKRD', name: 'Dockyard Road', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-dlv', code: 'DLV', name: 'Dolavli', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-di', code: 'DI', name: 'Dombivli', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-drng', code: 'DRNG', name: 'Dronagiri', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-gavn', code: 'GAVN', name: 'Gavan', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-gnsl', code: 'GNSL', name: 'Ghansoli', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-gc', code: 'GC', name: 'Ghatkopar', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-gvd', code: 'GVD', name: 'Gholwad', city: 'Palghar', state: 'Maharashtra' },
    { id: 'st-gmn', code: 'GMN', name: 'Goregaon', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-gv', code: 'GV', name: 'Govandi', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-gtr', code: 'GTR', name: 'Grant Road', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-gtbn', code: 'GTBN', name: 'Guru Tegh Bahadur Nagar', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-hmrr', code: 'HMRR', name: 'Hamrapur', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-jite', code: 'JITE', name: 'Jite', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-jos', code: 'JOS', name: 'Jogeshwari', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-jcnr', code: 'JCNR', name: 'Juchandra', city: 'Palghar', state: 'Maharashtra' },
    { id: 'st-jnj', code: 'JNJ', name: 'Juinagar', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-jmpi', code: 'JMPI', name: 'Jummapatti', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-klmg', code: 'KLMG', name: 'Kalamboli', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-klva', code: 'KLVA', name: 'Kalwa', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-kyn', code: 'KYN', name: 'Kalyan Junction', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-kav', code: 'KAV', name: 'Kaman Road', city: 'Palghar', state: 'Maharashtra' },
    { id: 'st-kile', code: 'KILE', name: 'Kandivli', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-kjmg', code: 'KJMG', name: 'Kanjur Marg', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-kjt', code: 'KJT', name: 'Karjat', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-ksra', code: 'KSRA', name: 'Kasara', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-kasu', code: 'KASU', name: 'Kasu', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-kvl', code: 'KVL', name: 'Kelavli', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-klv', code: 'KLV', name: 'Kelve Road', city: 'Palghar', state: 'Maharashtra' },
    { id: 'st-kdv', code: 'KDV', name: 'Khadavli', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-knds', code: 'KNDS', name: 'Khandeshwar', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-khar', code: 'KHAR', name: 'Khar Road', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-khbv', code: 'KHBV', name: 'Kharbav', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-kard', code: 'KARD', name: 'Khardi', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-khag', code: 'KHAG', name: 'Kharghar', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-karp', code: 'KARP', name: 'Kharkopar', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-khpi', code: 'KHPI', name: 'Khopoli', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-kce', code: 'KCE', name: 'King\'s Circle', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-kopr', code: 'KOPR', name: 'Kopar', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-kphn', code: 'KPHN', name: 'Koparkhairane', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-cla', code: 'CLA', name: 'Kurla', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-ltt', code: 'LTT', name: 'Lokmanya Tilak Terminus', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-pl', code: 'PL', name: 'Lower Parel', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-lwj', code: 'LWJ', name: 'Lowjee', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-mx', code: 'MX', name: 'Mahalaxmi', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-mm', code: 'MM', name: 'Mahim Junction', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-mdd', code: 'MDD', name: 'Malad', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-mnkd', code: 'MNKD', name: 'Mankhurd', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-manr', code: 'MANR', name: 'Mansarovar', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-mel', code: 'MEL', name: 'Marine Lines', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-msd', code: 'MSD', name: 'Masjid', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-mhn', code: 'MHN', name: 'Matheran', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-mtn', code: 'MTN', name: 'Matunga', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-mru', code: 'MRU', name: 'Matunga Road', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-mira', code: 'MIRA', name: 'Mira Road', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-mlnd', code: 'MLND', name: 'Mulund', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-mmct', code: 'MMCT', name: 'Mumbai Central', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-mbq', code: 'MBQ', name: 'Mumbra', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-nng', code: 'NNG', name: 'Nagothane', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-nhu', code: 'NHU', name: 'Nahur', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-nig', code: 'NIG', name: 'Naigaon', city: 'Palghar', state: 'Maharashtra' },
    { id: 'st-nsp', code: 'NSP', name: 'Nallasopara', city: 'Palghar', state: 'Maharashtra' },
    { id: 'st-nvrd', code: 'NVRD', name: 'Navde Road', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-nrl', code: 'NRL', name: 'Neral Junction', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-neu', code: 'NEU', name: 'Nerul', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-nwsh', code: 'NWSH', name: 'Nhava Sheva', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-nidi', code: 'NIDI', name: 'Nidi', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-niij', code: 'NIIJ', name: 'Nilaje', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-pdi', code: 'PDI', name: 'Palasdhari', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-plg', code: 'PLG', name: 'Palghar', city: 'Palghar', state: 'Maharashtra' },
    { id: 'st-pnvl', code: 'PNVL', name: 'Panvel', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-pr', code: 'PR', name: 'Parel', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-pen', code: 'PEN', name: 'Pen', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-pyje', code: 'PYJE', name: 'Poyanje', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-pbhd', code: 'PBHD', name: 'Prabhadevi', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-rabe', code: 'RABE', name: 'Rabale', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-rmar', code: 'RMAR', name: 'Ram Mandir', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-rsyi', code: 'RSYI', name: 'Rasayani', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-rrd', code: 'RRD', name: 'Reay Road', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-roha', code: 'ROHA', name: 'Roha', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-snrd', code: 'SNRD', name: 'Sandhurst Road', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-sncr', code: 'SNCR', name: 'Sanpada', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-stc', code: 'STC', name: 'Santacruz', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-sah', code: 'SAH', name: 'Saphale', city: 'Palghar', state: 'Maharashtra' },
    { id: 'st-swdv', code: 'SWDV', name: 'Seawoods-Darave-Karave', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-sve', code: 'SVE', name: 'Sewri', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-shad', code: 'SHAD', name: 'Shahad', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-shlu', code: 'SHLU', name: 'Shelu', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-semk', code: 'SEMK', name: 'Shematikhar', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-sin', code: 'SIN', name: 'Sion', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-smne', code: 'SMNE', name: 'Somatne', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-tpnd', code: 'TPND', name: 'Taloje Panchnand', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-trgr', code: 'TRGR', name: 'Targhar', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-thk', code: 'THK', name: 'Thakurli', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-tna', code: 'TNA', name: 'Thane', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-ths', code: 'THS', name: 'Thansit', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-tkng', code: 'TKNG', name: 'Tilak Nagar', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-tla', code: 'TLA', name: 'Titwala', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-trb', code: 'TRB', name: 'Turbhe', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-ulnr', code: 'ULNR', name: 'Ulhasnagar', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-omb', code: 'OMB', name: 'Umbermali', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-uoi', code: 'UOI', name: 'Umroli', city: 'Palghar', state: 'Maharashtra' },
    { id: 'st-uran', code: 'URAN', name: 'Uran', city: 'Raigad', state: 'Maharashtra' },
    { id: 'st-vtn', code: 'VTN', name: 'Vaitarna', city: 'Palghar', state: 'Maharashtra' },
    { id: 'st-vgi', code: 'VGI', name: 'Vangani', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-vgn', code: 'VGN', name: 'Vangaon', city: 'Palghar', state: 'Maharashtra' },
    { id: 'st-bsr', code: 'BSR', name: 'Vasai Road', city: 'Palghar', state: 'Maharashtra' },
    { id: 'st-vsh', code: 'VSH', name: 'Vashi', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-vsd', code: 'VSD', name: 'Vasind', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-vvh', code: 'VVH', name: 'Vidyavihar', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-vk', code: 'VK', name: 'Vikhroli', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-vlp', code: 'VLP', name: 'Vile Parle', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-vr', code: 'VR', name: 'Virar', city: 'Palghar', state: 'Maharashtra' },
    { id: 'st-vldi', code: 'VLDI', name: 'Vithalwadi', city: 'Thane', state: 'Maharashtra' },
    { id: 'st-vdlr', code: 'VDLR', name: 'Wadala Road', city: 'Mumbai', state: 'Maharashtra' },
    { id: 'st-wpi', code: 'WPI', name: 'Water Pipe', city: 'Raigad', state: 'Maharashtra' },
  ];
  const coordMap: Record<string, { lat: number; lng: number }> = {
    NDLS: { lat: 28.6143, lng: 77.2198 },
    MAS: { lat: 13.0827, lng: 80.2707 },
    HWH: { lat: 22.5851, lng: 88.3378 },
    SBC: { lat: 12.9784, lng: 77.5694 },
    PUNE: { lat: 18.5308, lng: 73.8741 },
    ADI: { lat: 23.0270, lng: 72.6012 },
    JP: { lat: 26.9200, lng: 75.7865 },
    HYB: { lat: 17.3916, lng: 78.4719 },
    BPL: { lat: 23.2625, lng: 77.4143 },
    PNBE: { lat: 25.6022, lng: 85.1200 },
    LKO: { lat: 26.8317, lng: 80.9220 },
    CSTM: { lat: 18.9400, lng: 72.8353 },
    CCG: { lat: 18.9322, lng: 72.8264 },
    BY: { lat: 18.9744, lng: 72.8339 },
    DR: { lat: 19.0178, lng: 72.8431 },
    CLA: { lat: 19.0652, lng: 72.8793 },
    GC: { lat: 19.0864, lng: 72.9080 },
    TNA: { lat: 19.1860, lng: 72.9757 },
    DI: { lat: 19.2184, lng: 73.0867 },
    KYN: { lat: 19.2354, lng: 73.1299 },
    PNVL: { lat: 18.9894, lng: 73.1175 },
    VSH: { lat: 19.0644, lng: 72.9975 },
    MMCT: { lat: 18.9696, lng: 72.8194 },
    BA: { lat: 19.0544, lng: 72.8406 },
    ADH: { lat: 19.1197, lng: 72.8468 },
    BVI: { lat: 19.2290, lng: 72.8573 },
    BYR: { lat: 19.2941, lng: 72.8550 },
    BSR: { lat: 19.3824, lng: 72.8317 },
    VR: { lat: 19.4674, lng: 72.7989 }
  };

  const stationsWithCoords = stations.map(s => {
    const coords = coordMap[s.code.toUpperCase()];
    return {
      ...s,
      latitude: coords ? coords.lat : null,
      longitude: coords ? coords.lng : null
    };
  });

  await prisma.station.createMany({ data: stationsWithCoords });
  console.log('[SUCCESS] Stations seeded with coordinates');


  // --- TRAINS --------------------------------------------------------------
  const trains = [
    // Express Trains
    { id: 'tr-12951', trainNumber: '12951', name: 'Mumbai Rajdhani Express', type: 'Rajdhani', fromStation: 'NDLS', toStation: 'CSTM', totalSeats: 1000 },
    { id: 'tr-12009', trainNumber: '12009', name: 'Shatabdi Express', type: 'Shatabdi', fromStation: 'CSTM', toStation: 'ADI', totalSeats: 800 },
    { id: 'tr-12263', trainNumber: '12263', name: 'Pune Nizamuddin Duronto', type: 'Duronto', fromStation: 'PUNE', toStation: 'NDLS', totalSeats: 900 },
    { id: 'tr-12627', trainNumber: '12627', name: 'Karnataka Express', type: 'Superfast', fromStation: 'SBC', toStation: 'NDLS', totalSeats: 1200 },
    { id: 'tr-12859', trainNumber: '12859', name: 'Gitanjali Express', type: 'Superfast', fromStation: 'CSTM', toStation: 'HWH', totalSeats: 1100 },
    { id: 'tr-dq',    trainNumber: '12124', name: 'Deccan Queen', type: 'Superfast', fromStation: 'PUNE', toStation: 'CSTM', totalSeats: 800 },
    { id: 'tr-dq-ret',trainNumber: '12123', name: 'Deccan Queen Return', type: 'Superfast', fromStation: 'CSTM', toStation: 'PUNE', totalSeats: 800 },
    { id: 'tr-kk',    trainNumber: '10111', name: 'Konkan Kanya Express', type: 'Express', fromStation: 'CSTM', toStation: 'PNVL', totalSeats: 900 },
    { id: 'tr-kk-ret',trainNumber: '10112', name: 'Konkan Kanya Return', type: 'Express', fromStation: 'PNVL', toStation: 'CSTM', totalSeats: 900 },
    
    // Western Line Locals
    { id: 'tr-wl-1', trainNumber: 'WR9001', name: 'Churchgate - Virar Fast', type: 'Local', fromStation: 'CCG', toStation: 'VR', totalSeats: 3000 },
    { id: 'tr-wl-2', trainNumber: 'WR9002', name: 'Virar - Churchgate Fast', type: 'Local', fromStation: 'VR', toStation: 'CCG', totalSeats: 3000 },
    { id: 'tr-wl-3', trainNumber: 'WR9003', name: 'Churchgate - Borivali Slow', type: 'Local', fromStation: 'CCG', toStation: 'BVI', totalSeats: 3000 },
    { id: 'tr-wl-4', trainNumber: 'WR9004', name: 'Borivali - Churchgate Slow', type: 'Local', fromStation: 'BVI', toStation: 'CCG', totalSeats: 3000 },
    { id: 'tr-wl-5', trainNumber: 'WR9005', name: 'Churchgate - Virar Slow', type: 'Local', fromStation: 'CCG', toStation: 'VR', totalSeats: 3000 },
    
    // Central Line Locals
    { id: 'tr-cl-1', trainNumber: 'CR8001', name: 'CSMT - Kalyan Fast', type: 'Local', fromStation: 'CSTM', toStation: 'KYN', totalSeats: 3000 },
    { id: 'tr-cl-2', trainNumber: 'CR8002', name: 'Kalyan - CSMT Fast', type: 'Local', fromStation: 'KYN', toStation: 'CSTM', totalSeats: 3000 },
    { id: 'tr-cl-3', trainNumber: 'CR8003', name: 'CSMT - Thane Slow', type: 'Local', fromStation: 'CSTM', toStation: 'TNA', totalSeats: 3000 },
    { id: 'tr-cl-4', trainNumber: 'CR8004', name: 'Thane - CSMT Slow', type: 'Local', fromStation: 'TNA', toStation: 'CSTM', totalSeats: 3000 },
    
    // Harbour Line Locals
    { id: 'tr-hl-1', trainNumber: 'HR7001', name: 'CSMT - Panvel Local', type: 'Local', fromStation: 'CSTM', toStation: 'PNVL', totalSeats: 3000 },
    { id: 'tr-hl-2', trainNumber: 'HR7002', name: 'Panvel - CSMT Local', type: 'Local', fromStation: 'PNVL', toStation: 'CSTM', totalSeats: 3000 },
    { id: 'tr-hl-3', trainNumber: 'HR7003', name: 'CSMT - Vashi Local', type: 'Local', fromStation: 'CSTM', toStation: 'VSH', totalSeats: 3000 },
    { id: 'tr-hl-4', trainNumber: 'HR7004', name: 'Vashi - CSMT Local', type: 'Local', fromStation: 'VSH', toStation: 'CSTM', totalSeats: 3000 },
  ];
  await prisma.train.createMany({ data: trains });
  console.log('[SUCCESS] Trains seeded');

  // --- TRAIN ROUTES --------------------------------------------------------
  const routes = [
    { id: 'r-1', trainId: 'tr-12951', stationId: 'st-cstm', stopNumber: 1, arrivalTime: null, departureTime: '17:00', distanceFromOrigin: 0, platform: '1', haltMinutes: 0 },
    { id: 'r-2', trainId: 'tr-12951', stationId: 'st-adi',  stopNumber: 2, arrivalTime: '22:30', departureTime: '22:40', distanceFromOrigin: 493, platform: '3', haltMinutes: 10 },
    { id: 'r-3', trainId: 'tr-12951', stationId: 'st-jp',   stopNumber: 3, arrivalTime: '05:00', departureTime: '05:10', distanceFromOrigin: 1100, platform: '1', haltMinutes: 10 },
    { id: 'r-4', trainId: 'tr-12951', stationId: 'st-ndls', stopNumber: 4, arrivalTime: '08:32', departureTime: null, distanceFromOrigin: 1384, platform: '3', haltMinutes: 0 },
    { id: 'r-sh-1', trainId: 'tr-12009', stationId: 'st-cstm', stopNumber: 1, arrivalTime: null, departureTime: '06:25', distanceFromOrigin: 0, platform: '3', haltMinutes: 0 },
    { id: 'r-sh-2', trainId: 'tr-12009', stationId: 'st-tna',  stopNumber: 2, arrivalTime: '06:50', departureTime: '06:52', distanceFromOrigin: 33, platform: '5', haltMinutes: 2 },
    { id: 'r-sh-3', trainId: 'tr-12009', stationId: 'st-bsr',  stopNumber: 3, arrivalTime: '07:35', departureTime: '07:37', distanceFromOrigin: 75, platform: '6', haltMinutes: 2 },
    { id: 'r-sh-4', trainId: 'tr-12009', stationId: 'st-adi',  stopNumber: 4, arrivalTime: '12:20', departureTime: null, distanceFromOrigin: 490, platform: '1', haltMinutes: 0 },
    { id: 'r-du-1', trainId: 'tr-12263', stationId: 'st-pune', stopNumber: 1, arrivalTime: null, departureTime: '11:10', distanceFromOrigin: 0, platform: '1', haltMinutes: 0 },
    { id: 'r-du-2', trainId: 'tr-12263', stationId: 'st-bsr',  stopNumber: 2, arrivalTime: '13:55', departureTime: '14:00', distanceFromOrigin: 150, platform: '6', haltMinutes: 5 },
    { id: 'r-du-3', trainId: 'tr-12263', stationId: 'st-adi',  stopNumber: 3, arrivalTime: '18:40', departureTime: '18:50', distanceFromOrigin: 490, platform: '3', haltMinutes: 10 },
    { id: 'r-du-4', trainId: 'tr-12263', stationId: 'st-ndls', stopNumber: 4, arrivalTime: '05:55', departureTime: null, distanceFromOrigin: 1380, platform: '4', haltMinutes: 0 },
    { id: 'r-ka-1', trainId: 'tr-12627', stationId: 'st-sbc',  stopNumber: 1, arrivalTime: null, departureTime: '19:20', distanceFromOrigin: 0, platform: '1', haltMinutes: 0 },
    { id: 'r-ka-2', trainId: 'tr-12627', stationId: 'st-pune', stopNumber: 2, arrivalTime: '08:45', departureTime: '08:55', distanceFromOrigin: 1000, platform: '2', haltMinutes: 10 },
    { id: 'r-ka-3', trainId: 'tr-12627', stationId: 'st-ndls', stopNumber: 3, arrivalTime: '05:40', departureTime: null, distanceFromOrigin: 2000, platform: '2', haltMinutes: 0 },
    { id: 'r-gi-1', trainId: 'tr-12859', stationId: 'st-cstm', stopNumber: 1, arrivalTime: null, departureTime: '06:00', distanceFromOrigin: 0, platform: '18', haltMinutes: 0 },
    { id: 'r-gi-2', trainId: 'tr-12859', stationId: 'st-dr',   stopNumber: 2, arrivalTime: '06:12', departureTime: '06:15', distanceFromOrigin: 9, platform: '5', haltMinutes: 3 },
    { id: 'r-gi-3', trainId: 'tr-12859', stationId: 'st-tna',  stopNumber: 3, arrivalTime: '06:33', departureTime: '06:35', distanceFromOrigin: 33, platform: '5', haltMinutes: 2 },
    { id: 'r-gi-4', trainId: 'tr-12859', stationId: 'st-kyn',  stopNumber: 4, arrivalTime: '06:53', departureTime: '06:55', distanceFromOrigin: 53, platform: '4', haltMinutes: 2 },
    { id: 'r-gi-5', trainId: 'tr-12859', stationId: 'st-pune', stopNumber: 5, arrivalTime: '09:40', departureTime: '09:45', distanceFromOrigin: 191, platform: '1', haltMinutes: 5 },
    { id: 'r-gi-6', trainId: 'tr-12859', stationId: 'st-hwh',  stopNumber: 6, arrivalTime: '12:30', departureTime: null, distanceFromOrigin: 1968, platform: '21', haltMinutes: 0 },
    { id: 'r-dq-1', trainId: 'tr-dq', stationId: 'st-pune', stopNumber: 1, arrivalTime: null, departureTime: '07:15', distanceFromOrigin: 0, platform: '1', haltMinutes: 0 },
    { id: 'r-dq-2', trainId: 'tr-dq', stationId: 'st-kyn',  stopNumber: 2, arrivalTime: '09:30', departureTime: '09:32', distanceFromOrigin: 138, platform: '6', haltMinutes: 2 },
    { id: 'r-dq-3', trainId: 'tr-dq', stationId: 'st-tna',  stopNumber: 3, arrivalTime: '09:50', departureTime: '09:52', distanceFromOrigin: 158, platform: '6', haltMinutes: 2 },
    { id: 'r-dq-4', trainId: 'tr-dq', stationId: 'st-dr',   stopNumber: 4, arrivalTime: '10:15', departureTime: '10:17', distanceFromOrigin: 182, platform: '6', haltMinutes: 2 },
    { id: 'r-dq-5', trainId: 'tr-dq', stationId: 'st-cstm', stopNumber: 5, arrivalTime: '10:30', departureTime: null, distanceFromOrigin: 191, platform: '8', haltMinutes: 0 },
    { id: 'r-dqr-1', trainId: 'tr-dq-ret', stationId: 'st-cstm', stopNumber: 1, arrivalTime: null, departureTime: '17:10', distanceFromOrigin: 0, platform: '8', haltMinutes: 0 },
    { id: 'r-dqr-2', trainId: 'tr-dq-ret', stationId: 'st-dr',   stopNumber: 2, arrivalTime: '17:22', departureTime: '17:24', distanceFromOrigin: 9, platform: '8', haltMinutes: 2 },
    { id: 'r-dqr-3', trainId: 'tr-dq-ret', stationId: 'st-tna',  stopNumber: 3, arrivalTime: '17:45', departureTime: '17:47', distanceFromOrigin: 33, platform: '7', haltMinutes: 2 },
    { id: 'r-dqr-4', trainId: 'tr-dq-ret', stationId: 'st-kyn',  stopNumber: 4, arrivalTime: '18:08', departureTime: '18:10', distanceFromOrigin: 53, platform: '5', haltMinutes: 2 },
    { id: 'r-dqr-5', trainId: 'tr-dq-ret', stationId: 'st-pune', stopNumber: 5, arrivalTime: '20:15', departureTime: null, distanceFromOrigin: 191, platform: '5', haltMinutes: 0 },
    { id: 'r-kk-1', trainId: 'tr-kk', stationId: 'st-cstm', stopNumber: 1, arrivalTime: null, departureTime: '23:05', distanceFromOrigin: 0, platform: '17', haltMinutes: 0 },
    { id: 'r-kk-2', trainId: 'tr-kk', stationId: 'st-dr',   stopNumber: 2, arrivalTime: '23:17', departureTime: '23:20', distanceFromOrigin: 9, platform: '7', haltMinutes: 3 },
    { id: 'r-kk-3', trainId: 'tr-kk', stationId: 'st-tna',  stopNumber: 3, arrivalTime: '23:42', departureTime: '23:45', distanceFromOrigin: 33, platform: '7', haltMinutes: 3 },
    { id: 'r-kk-4', trainId: 'tr-kk', stationId: 'st-pnvl', stopNumber: 4, arrivalTime: '00:30', departureTime: null, distanceFromOrigin: 68, platform: '2', haltMinutes: 0 },
    { id: 'r-kkr-1', trainId: 'tr-kk-ret', stationId: 'st-pnvl', stopNumber: 1, arrivalTime: null, departureTime: '04:15', distanceFromOrigin: 0, platform: '2', haltMinutes: 0 },
    { id: 'r-kkr-2', trainId: 'tr-kk-ret', stationId: 'st-tna',  stopNumber: 2, arrivalTime: '05:00', departureTime: '05:03', distanceFromOrigin: 35, platform: '7', haltMinutes: 3 },
    { id: 'r-kkr-3', trainId: 'tr-kk-ret', stationId: 'st-dr',   stopNumber: 3, arrivalTime: '05:25', departureTime: '05:28', distanceFromOrigin: 59, platform: '6', haltMinutes: 3 },
    { id: 'r-kkr-4', trainId: 'tr-kk-ret', stationId: 'st-cstm', stopNumber: 4, arrivalTime: '05:45', departureTime: null, distanceFromOrigin: 68, platform: '17', haltMinutes: 0 },
    { id: 'r-tr-wl-1-ccg', trainId: 'tr-wl-1', stationId: 'st-ccg', stopNumber: 1, arrivalTime: null, departureTime: '08:00', distanceFromOrigin: 0, platform: '2', haltMinutes: 0 },
    { id: 'r-tr-wl-1-mmct', trainId: 'tr-wl-1', stationId: 'st-mmct', stopNumber: 2, arrivalTime: '08:05', departureTime: '08:06', distanceFromOrigin: 10, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-wl-1-dr', trainId: 'tr-wl-1', stationId: 'st-dr', stopNumber: 3, arrivalTime: '08:11', departureTime: '08:12', distanceFromOrigin: 20, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-wl-1-ba', trainId: 'tr-wl-1', stationId: 'st-ba', stopNumber: 4, arrivalTime: '08:17', departureTime: '08:18', distanceFromOrigin: 30, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-wl-1-adh', trainId: 'tr-wl-1', stationId: 'st-adh', stopNumber: 5, arrivalTime: '08:23', departureTime: '08:24', distanceFromOrigin: 40, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-wl-1-bvi', trainId: 'tr-wl-1', stationId: 'st-bvi', stopNumber: 6, arrivalTime: '08:29', departureTime: '08:30', distanceFromOrigin: 50, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-wl-1-byr', trainId: 'tr-wl-1', stationId: 'st-byr', stopNumber: 7, arrivalTime: '08:35', departureTime: '08:36', distanceFromOrigin: 60, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-wl-1-bsr', trainId: 'tr-wl-1', stationId: 'st-bsr', stopNumber: 8, arrivalTime: '08:41', departureTime: '08:42', distanceFromOrigin: 70, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-wl-1-vr', trainId: 'tr-wl-1', stationId: 'st-vr', stopNumber: 9, arrivalTime: '08:47', departureTime: null, distanceFromOrigin: 80, platform: '2', haltMinutes: 0 },
    { id: 'r-tr-wl-2-vr', trainId: 'tr-wl-2', stationId: 'st-vr', stopNumber: 1, arrivalTime: null, departureTime: '09:30', distanceFromOrigin: 0, platform: '2', haltMinutes: 0 },
    { id: 'r-tr-wl-2-bsr', trainId: 'tr-wl-2', stationId: 'st-bsr', stopNumber: 2, arrivalTime: '09:35', departureTime: '09:36', distanceFromOrigin: 10, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-wl-2-byr', trainId: 'tr-wl-2', stationId: 'st-byr', stopNumber: 3, arrivalTime: '09:41', departureTime: '09:42', distanceFromOrigin: 20, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-wl-2-bvi', trainId: 'tr-wl-2', stationId: 'st-bvi', stopNumber: 4, arrivalTime: '09:47', departureTime: '09:48', distanceFromOrigin: 30, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-wl-2-adh', trainId: 'tr-wl-2', stationId: 'st-adh', stopNumber: 5, arrivalTime: '09:53', departureTime: '09:54', distanceFromOrigin: 40, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-wl-2-ba', trainId: 'tr-wl-2', stationId: 'st-ba', stopNumber: 6, arrivalTime: '09:59', departureTime: '10:00', distanceFromOrigin: 50, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-wl-2-dr', trainId: 'tr-wl-2', stationId: 'st-dr', stopNumber: 7, arrivalTime: '10:05', departureTime: '10:06', distanceFromOrigin: 60, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-wl-2-mmct', trainId: 'tr-wl-2', stationId: 'st-mmct', stopNumber: 8, arrivalTime: '10:11', departureTime: '10:12', distanceFromOrigin: 70, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-wl-2-ccg', trainId: 'tr-wl-2', stationId: 'st-ccg', stopNumber: 9, arrivalTime: '10:17', departureTime: null, distanceFromOrigin: 80, platform: '2', haltMinutes: 0 },
    { id: 'r-tr-wl-3-ccg', trainId: 'tr-wl-3', stationId: 'st-ccg', stopNumber: 1, arrivalTime: null, departureTime: '08:15', distanceFromOrigin: 0, platform: '2', haltMinutes: 0 },
    { id: 'r-tr-wl-3-mel', trainId: 'tr-wl-3', stationId: 'st-mel', stopNumber: 2, arrivalTime: '08:17', departureTime: '08:18', distanceFromOrigin: 2, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-wl-3-cyr', trainId: 'tr-wl-3', stationId: 'st-cyr', stopNumber: 3, arrivalTime: '08:20', departureTime: '08:21', distanceFromOrigin: 4, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-wl-3-gtr', trainId: 'tr-wl-3', stationId: 'st-gtr', stopNumber: 4, arrivalTime: '08:23', departureTime: '08:24', distanceFromOrigin: 6, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-wl-3-mmct', trainId: 'tr-wl-3', stationId: 'st-mmct', stopNumber: 5, arrivalTime: '08:26', departureTime: '08:27', distanceFromOrigin: 8, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-wl-3-mx', trainId: 'tr-wl-3', stationId: 'st-mx', stopNumber: 6, arrivalTime: '08:29', departureTime: '08:30', distanceFromOrigin: 10, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-wl-3-pl', trainId: 'tr-wl-3', stationId: 'st-pl', stopNumber: 7, arrivalTime: '08:32', departureTime: '08:33', distanceFromOrigin: 12, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-wl-3-pbhd', trainId: 'tr-wl-3', stationId: 'st-pbhd', stopNumber: 8, arrivalTime: '08:35', departureTime: '08:36', distanceFromOrigin: 14, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-wl-3-dr', trainId: 'tr-wl-3', stationId: 'st-dr', stopNumber: 9, arrivalTime: '08:38', departureTime: '08:39', distanceFromOrigin: 16, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-wl-3-mru', trainId: 'tr-wl-3', stationId: 'st-mru', stopNumber: 10, arrivalTime: '08:41', departureTime: '08:42', distanceFromOrigin: 18, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-wl-3-mm', trainId: 'tr-wl-3', stationId: 'st-mm', stopNumber: 11, arrivalTime: '08:44', departureTime: '08:45', distanceFromOrigin: 20, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-wl-3-ba', trainId: 'tr-wl-3', stationId: 'st-ba', stopNumber: 12, arrivalTime: '08:47', departureTime: '08:48', distanceFromOrigin: 22, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-wl-3-khar', trainId: 'tr-wl-3', stationId: 'st-khar', stopNumber: 13, arrivalTime: '08:50', departureTime: '08:51', distanceFromOrigin: 24, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-wl-3-stc', trainId: 'tr-wl-3', stationId: 'st-stc', stopNumber: 14, arrivalTime: '08:53', departureTime: '08:54', distanceFromOrigin: 26, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-wl-3-vlp', trainId: 'tr-wl-3', stationId: 'st-vlp', stopNumber: 15, arrivalTime: '08:56', departureTime: '08:57', distanceFromOrigin: 28, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-wl-3-adh', trainId: 'tr-wl-3', stationId: 'st-adh', stopNumber: 16, arrivalTime: '08:59', departureTime: '09:00', distanceFromOrigin: 30, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-wl-3-jos', trainId: 'tr-wl-3', stationId: 'st-jos', stopNumber: 17, arrivalTime: '09:02', departureTime: '09:03', distanceFromOrigin: 32, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-wl-3-rmar', trainId: 'tr-wl-3', stationId: 'st-rmar', stopNumber: 18, arrivalTime: '09:05', departureTime: '09:06', distanceFromOrigin: 34, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-wl-3-gmn', trainId: 'tr-wl-3', stationId: 'st-gmn', stopNumber: 19, arrivalTime: '09:08', departureTime: '09:09', distanceFromOrigin: 36, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-wl-3-mdd', trainId: 'tr-wl-3', stationId: 'st-mdd', stopNumber: 20, arrivalTime: '09:11', departureTime: '09:12', distanceFromOrigin: 38, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-wl-3-kile', trainId: 'tr-wl-3', stationId: 'st-kile', stopNumber: 21, arrivalTime: '09:14', departureTime: '09:15', distanceFromOrigin: 40, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-wl-3-bvi', trainId: 'tr-wl-3', stationId: 'st-bvi', stopNumber: 22, arrivalTime: '09:18', departureTime: null, distanceFromOrigin: 42, platform: '3', haltMinutes: 0 },
    { id: 'r-tr-wl-4-bvi', trainId: 'tr-wl-4', stationId: 'st-bvi', stopNumber: 1, arrivalTime: null, departureTime: '09:45', distanceFromOrigin: 0, platform: '2', haltMinutes: 0 },
    { id: 'r-tr-wl-4-kile', trainId: 'tr-wl-4', stationId: 'st-kile', stopNumber: 2, arrivalTime: '09:47', departureTime: '09:48', distanceFromOrigin: 2, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-wl-4-mdd', trainId: 'tr-wl-4', stationId: 'st-mdd', stopNumber: 3, arrivalTime: '09:50', departureTime: '09:51', distanceFromOrigin: 4, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-wl-4-gmn', trainId: 'tr-wl-4', stationId: 'st-gmn', stopNumber: 4, arrivalTime: '09:53', departureTime: '09:54', distanceFromOrigin: 6, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-wl-4-rmar', trainId: 'tr-wl-4', stationId: 'st-rmar', stopNumber: 5, arrivalTime: '09:56', departureTime: '09:57', distanceFromOrigin: 8, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-wl-4-jos', trainId: 'tr-wl-4', stationId: 'st-jos', stopNumber: 6, arrivalTime: '09:59', departureTime: '10:00', distanceFromOrigin: 10, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-wl-4-adh', trainId: 'tr-wl-4', stationId: 'st-adh', stopNumber: 7, arrivalTime: '10:02', departureTime: '10:03', distanceFromOrigin: 12, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-wl-4-vlp', trainId: 'tr-wl-4', stationId: 'st-vlp', stopNumber: 8, arrivalTime: '10:05', departureTime: '10:06', distanceFromOrigin: 14, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-wl-4-stc', trainId: 'tr-wl-4', stationId: 'st-stc', stopNumber: 9, arrivalTime: '10:08', departureTime: '10:09', distanceFromOrigin: 16, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-wl-4-khar', trainId: 'tr-wl-4', stationId: 'st-khar', stopNumber: 10, arrivalTime: '10:11', departureTime: '10:12', distanceFromOrigin: 18, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-wl-4-ba', trainId: 'tr-wl-4', stationId: 'st-ba', stopNumber: 11, arrivalTime: '10:14', departureTime: '10:15', distanceFromOrigin: 20, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-wl-4-mm', trainId: 'tr-wl-4', stationId: 'st-mm', stopNumber: 12, arrivalTime: '10:17', departureTime: '10:18', distanceFromOrigin: 22, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-wl-4-mru', trainId: 'tr-wl-4', stationId: 'st-mru', stopNumber: 13, arrivalTime: '10:20', departureTime: '10:21', distanceFromOrigin: 24, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-wl-4-dr', trainId: 'tr-wl-4', stationId: 'st-dr', stopNumber: 14, arrivalTime: '10:23', departureTime: '10:24', distanceFromOrigin: 26, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-wl-4-pbhd', trainId: 'tr-wl-4', stationId: 'st-pbhd', stopNumber: 15, arrivalTime: '10:26', departureTime: '10:27', distanceFromOrigin: 28, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-wl-4-pl', trainId: 'tr-wl-4', stationId: 'st-pl', stopNumber: 16, arrivalTime: '10:29', departureTime: '10:30', distanceFromOrigin: 30, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-wl-4-mx', trainId: 'tr-wl-4', stationId: 'st-mx', stopNumber: 17, arrivalTime: '10:32', departureTime: '10:33', distanceFromOrigin: 32, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-wl-4-mmct', trainId: 'tr-wl-4', stationId: 'st-mmct', stopNumber: 18, arrivalTime: '10:35', departureTime: '10:36', distanceFromOrigin: 34, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-wl-4-gtr', trainId: 'tr-wl-4', stationId: 'st-gtr', stopNumber: 19, arrivalTime: '10:38', departureTime: '10:39', distanceFromOrigin: 36, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-wl-4-cyr', trainId: 'tr-wl-4', stationId: 'st-cyr', stopNumber: 20, arrivalTime: '10:41', departureTime: '10:42', distanceFromOrigin: 38, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-wl-4-mel', trainId: 'tr-wl-4', stationId: 'st-mel', stopNumber: 21, arrivalTime: '10:44', departureTime: '10:45', distanceFromOrigin: 40, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-wl-4-ccg', trainId: 'tr-wl-4', stationId: 'st-ccg', stopNumber: 22, arrivalTime: '10:48', departureTime: null, distanceFromOrigin: 42, platform: '3', haltMinutes: 0 },
    { id: 'r-tr-wl-5-ccg', trainId: 'tr-wl-5', stationId: 'st-ccg', stopNumber: 1, arrivalTime: null, departureTime: '08:30', distanceFromOrigin: 0, platform: '2', haltMinutes: 0 },
    { id: 'r-tr-wl-5-mel', trainId: 'tr-wl-5', stationId: 'st-mel', stopNumber: 2, arrivalTime: '08:32', departureTime: '08:33', distanceFromOrigin: 2, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-wl-5-cyr', trainId: 'tr-wl-5', stationId: 'st-cyr', stopNumber: 3, arrivalTime: '08:35', departureTime: '08:36', distanceFromOrigin: 4, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-wl-5-gtr', trainId: 'tr-wl-5', stationId: 'st-gtr', stopNumber: 4, arrivalTime: '08:38', departureTime: '08:39', distanceFromOrigin: 6, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-wl-5-mmct', trainId: 'tr-wl-5', stationId: 'st-mmct', stopNumber: 5, arrivalTime: '08:41', departureTime: '08:42', distanceFromOrigin: 8, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-wl-5-mx', trainId: 'tr-wl-5', stationId: 'st-mx', stopNumber: 6, arrivalTime: '08:44', departureTime: '08:45', distanceFromOrigin: 10, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-wl-5-pl', trainId: 'tr-wl-5', stationId: 'st-pl', stopNumber: 7, arrivalTime: '08:47', departureTime: '08:48', distanceFromOrigin: 12, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-wl-5-pbhd', trainId: 'tr-wl-5', stationId: 'st-pbhd', stopNumber: 8, arrivalTime: '08:50', departureTime: '08:51', distanceFromOrigin: 14, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-wl-5-dr', trainId: 'tr-wl-5', stationId: 'st-dr', stopNumber: 9, arrivalTime: '08:53', departureTime: '08:54', distanceFromOrigin: 16, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-wl-5-mru', trainId: 'tr-wl-5', stationId: 'st-mru', stopNumber: 10, arrivalTime: '08:56', departureTime: '08:57', distanceFromOrigin: 18, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-wl-5-mm', trainId: 'tr-wl-5', stationId: 'st-mm', stopNumber: 11, arrivalTime: '08:59', departureTime: '09:00', distanceFromOrigin: 20, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-wl-5-ba', trainId: 'tr-wl-5', stationId: 'st-ba', stopNumber: 12, arrivalTime: '09:02', departureTime: '09:03', distanceFromOrigin: 22, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-wl-5-khar', trainId: 'tr-wl-5', stationId: 'st-khar', stopNumber: 13, arrivalTime: '09:05', departureTime: '09:06', distanceFromOrigin: 24, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-wl-5-stc', trainId: 'tr-wl-5', stationId: 'st-stc', stopNumber: 14, arrivalTime: '09:08', departureTime: '09:09', distanceFromOrigin: 26, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-wl-5-vlp', trainId: 'tr-wl-5', stationId: 'st-vlp', stopNumber: 15, arrivalTime: '09:11', departureTime: '09:12', distanceFromOrigin: 28, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-wl-5-adh', trainId: 'tr-wl-5', stationId: 'st-adh', stopNumber: 16, arrivalTime: '09:14', departureTime: '09:15', distanceFromOrigin: 30, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-wl-5-jos', trainId: 'tr-wl-5', stationId: 'st-jos', stopNumber: 17, arrivalTime: '09:17', departureTime: '09:18', distanceFromOrigin: 32, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-wl-5-rmar', trainId: 'tr-wl-5', stationId: 'st-rmar', stopNumber: 18, arrivalTime: '09:20', departureTime: '09:21', distanceFromOrigin: 34, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-wl-5-gmn', trainId: 'tr-wl-5', stationId: 'st-gmn', stopNumber: 19, arrivalTime: '09:23', departureTime: '09:24', distanceFromOrigin: 36, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-wl-5-mdd', trainId: 'tr-wl-5', stationId: 'st-mdd', stopNumber: 20, arrivalTime: '09:26', departureTime: '09:27', distanceFromOrigin: 38, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-wl-5-kile', trainId: 'tr-wl-5', stationId: 'st-kile', stopNumber: 21, arrivalTime: '09:29', departureTime: '09:30', distanceFromOrigin: 40, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-wl-5-bvi', trainId: 'tr-wl-5', stationId: 'st-bvi', stopNumber: 22, arrivalTime: '09:32', departureTime: '09:33', distanceFromOrigin: 42, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-wl-5-dic', trainId: 'tr-wl-5', stationId: 'st-dic', stopNumber: 23, arrivalTime: '09:35', departureTime: '09:36', distanceFromOrigin: 44, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-wl-5-mira', trainId: 'tr-wl-5', stationId: 'st-mira', stopNumber: 24, arrivalTime: '09:38', departureTime: '09:39', distanceFromOrigin: 46, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-wl-5-byr', trainId: 'tr-wl-5', stationId: 'st-byr', stopNumber: 25, arrivalTime: '09:41', departureTime: '09:42', distanceFromOrigin: 48, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-wl-5-nig', trainId: 'tr-wl-5', stationId: 'st-nig', stopNumber: 26, arrivalTime: '09:44', departureTime: '09:45', distanceFromOrigin: 50, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-wl-5-bsr', trainId: 'tr-wl-5', stationId: 'st-bsr', stopNumber: 27, arrivalTime: '09:47', departureTime: '09:48', distanceFromOrigin: 52, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-wl-5-nsp', trainId: 'tr-wl-5', stationId: 'st-nsp', stopNumber: 28, arrivalTime: '09:50', departureTime: '09:51', distanceFromOrigin: 54, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-wl-5-vr', trainId: 'tr-wl-5', stationId: 'st-vr', stopNumber: 29, arrivalTime: '09:54', departureTime: null, distanceFromOrigin: 56, platform: '2', haltMinutes: 0 },
    { id: 'r-tr-cl-1-cstm', trainId: 'tr-cl-1', stationId: 'st-cstm', stopNumber: 1, arrivalTime: null, departureTime: '09:00', distanceFromOrigin: 0, platform: '2', haltMinutes: 0 },
    { id: 'r-tr-cl-1-by', trainId: 'tr-cl-1', stationId: 'st-by', stopNumber: 2, arrivalTime: '09:05', departureTime: '09:06', distanceFromOrigin: 10, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-cl-1-dr', trainId: 'tr-cl-1', stationId: 'st-dr', stopNumber: 3, arrivalTime: '09:11', departureTime: '09:12', distanceFromOrigin: 20, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-cl-1-cla', trainId: 'tr-cl-1', stationId: 'st-cla', stopNumber: 4, arrivalTime: '09:17', departureTime: '09:18', distanceFromOrigin: 30, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-cl-1-gc', trainId: 'tr-cl-1', stationId: 'st-gc', stopNumber: 5, arrivalTime: '09:23', departureTime: '09:24', distanceFromOrigin: 40, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-cl-1-tna', trainId: 'tr-cl-1', stationId: 'st-tna', stopNumber: 6, arrivalTime: '09:29', departureTime: '09:30', distanceFromOrigin: 50, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-cl-1-di', trainId: 'tr-cl-1', stationId: 'st-di', stopNumber: 7, arrivalTime: '09:35', departureTime: '09:36', distanceFromOrigin: 60, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-cl-1-kyn', trainId: 'tr-cl-1', stationId: 'st-kyn', stopNumber: 8, arrivalTime: '09:41', departureTime: null, distanceFromOrigin: 70, platform: '1', haltMinutes: 0 },
    { id: 'r-tr-cl-2-kyn', trainId: 'tr-cl-2', stationId: 'st-kyn', stopNumber: 1, arrivalTime: null, departureTime: '10:30', distanceFromOrigin: 0, platform: '2', haltMinutes: 0 },
    { id: 'r-tr-cl-2-di', trainId: 'tr-cl-2', stationId: 'st-di', stopNumber: 2, arrivalTime: '10:35', departureTime: '10:36', distanceFromOrigin: 10, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-cl-2-tna', trainId: 'tr-cl-2', stationId: 'st-tna', stopNumber: 3, arrivalTime: '10:41', departureTime: '10:42', distanceFromOrigin: 20, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-cl-2-gc', trainId: 'tr-cl-2', stationId: 'st-gc', stopNumber: 4, arrivalTime: '10:47', departureTime: '10:48', distanceFromOrigin: 30, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-cl-2-cla', trainId: 'tr-cl-2', stationId: 'st-cla', stopNumber: 5, arrivalTime: '10:53', departureTime: '10:54', distanceFromOrigin: 40, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-cl-2-dr', trainId: 'tr-cl-2', stationId: 'st-dr', stopNumber: 6, arrivalTime: '10:59', departureTime: '11:00', distanceFromOrigin: 50, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-cl-2-by', trainId: 'tr-cl-2', stationId: 'st-by', stopNumber: 7, arrivalTime: '11:05', departureTime: '11:06', distanceFromOrigin: 60, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-cl-2-cstm', trainId: 'tr-cl-2', stationId: 'st-cstm', stopNumber: 8, arrivalTime: '11:11', departureTime: null, distanceFromOrigin: 70, platform: '1', haltMinutes: 0 },
    { id: 'r-tr-cl-3-cstm', trainId: 'tr-cl-3', stationId: 'st-cstm', stopNumber: 1, arrivalTime: null, departureTime: '09:15', distanceFromOrigin: 0, platform: '2', haltMinutes: 0 },
    { id: 'r-tr-cl-3-msd', trainId: 'tr-cl-3', stationId: 'st-msd', stopNumber: 2, arrivalTime: '09:17', departureTime: '09:18', distanceFromOrigin: 2, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-cl-3-snrd', trainId: 'tr-cl-3', stationId: 'st-snrd', stopNumber: 3, arrivalTime: '09:20', departureTime: '09:21', distanceFromOrigin: 4, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-cl-3-by', trainId: 'tr-cl-3', stationId: 'st-by', stopNumber: 4, arrivalTime: '09:23', departureTime: '09:24', distanceFromOrigin: 6, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-cl-3-chg', trainId: 'tr-cl-3', stationId: 'st-chg', stopNumber: 5, arrivalTime: '09:26', departureTime: '09:27', distanceFromOrigin: 8, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-cl-3-crd', trainId: 'tr-cl-3', stationId: 'st-crd', stopNumber: 6, arrivalTime: '09:29', departureTime: '09:30', distanceFromOrigin: 10, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-cl-3-pr', trainId: 'tr-cl-3', stationId: 'st-pr', stopNumber: 7, arrivalTime: '09:32', departureTime: '09:33', distanceFromOrigin: 12, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-cl-3-dr', trainId: 'tr-cl-3', stationId: 'st-dr', stopNumber: 8, arrivalTime: '09:35', departureTime: '09:36', distanceFromOrigin: 14, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-cl-3-mtn', trainId: 'tr-cl-3', stationId: 'st-mtn', stopNumber: 9, arrivalTime: '09:38', departureTime: '09:39', distanceFromOrigin: 16, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-cl-3-sin', trainId: 'tr-cl-3', stationId: 'st-sin', stopNumber: 10, arrivalTime: '09:41', departureTime: '09:42', distanceFromOrigin: 18, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-cl-3-cla', trainId: 'tr-cl-3', stationId: 'st-cla', stopNumber: 11, arrivalTime: '09:44', departureTime: '09:45', distanceFromOrigin: 20, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-cl-3-vvh', trainId: 'tr-cl-3', stationId: 'st-vvh', stopNumber: 12, arrivalTime: '09:47', departureTime: '09:48', distanceFromOrigin: 22, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-cl-3-gc', trainId: 'tr-cl-3', stationId: 'st-gc', stopNumber: 13, arrivalTime: '09:50', departureTime: '09:51', distanceFromOrigin: 24, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-cl-3-vk', trainId: 'tr-cl-3', stationId: 'st-vk', stopNumber: 14, arrivalTime: '09:53', departureTime: '09:54', distanceFromOrigin: 26, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-cl-3-kjmg', trainId: 'tr-cl-3', stationId: 'st-kjmg', stopNumber: 15, arrivalTime: '09:56', departureTime: '09:57', distanceFromOrigin: 28, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-cl-3-bnd', trainId: 'tr-cl-3', stationId: 'st-bnd', stopNumber: 16, arrivalTime: '09:59', departureTime: '10:00', distanceFromOrigin: 30, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-cl-3-nhu', trainId: 'tr-cl-3', stationId: 'st-nhu', stopNumber: 17, arrivalTime: '10:02', departureTime: '10:03', distanceFromOrigin: 32, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-cl-3-mlnd', trainId: 'tr-cl-3', stationId: 'st-mlnd', stopNumber: 18, arrivalTime: '10:05', departureTime: '10:06', distanceFromOrigin: 34, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-cl-3-tna', trainId: 'tr-cl-3', stationId: 'st-tna', stopNumber: 19, arrivalTime: '10:09', departureTime: null, distanceFromOrigin: 36, platform: '4', haltMinutes: 0 },
    { id: 'r-tr-cl-4-tna', trainId: 'tr-cl-4', stationId: 'st-tna', stopNumber: 1, arrivalTime: null, departureTime: '10:45', distanceFromOrigin: 0, platform: '2', haltMinutes: 0 },
    { id: 'r-tr-cl-4-mlnd', trainId: 'tr-cl-4', stationId: 'st-mlnd', stopNumber: 2, arrivalTime: '10:47', departureTime: '10:48', distanceFromOrigin: 2, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-cl-4-nhu', trainId: 'tr-cl-4', stationId: 'st-nhu', stopNumber: 3, arrivalTime: '10:50', departureTime: '10:51', distanceFromOrigin: 4, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-cl-4-bnd', trainId: 'tr-cl-4', stationId: 'st-bnd', stopNumber: 4, arrivalTime: '10:53', departureTime: '10:54', distanceFromOrigin: 6, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-cl-4-kjmg', trainId: 'tr-cl-4', stationId: 'st-kjmg', stopNumber: 5, arrivalTime: '10:56', departureTime: '10:57', distanceFromOrigin: 8, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-cl-4-vk', trainId: 'tr-cl-4', stationId: 'st-vk', stopNumber: 6, arrivalTime: '10:59', departureTime: '11:00', distanceFromOrigin: 10, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-cl-4-gc', trainId: 'tr-cl-4', stationId: 'st-gc', stopNumber: 7, arrivalTime: '11:02', departureTime: '11:03', distanceFromOrigin: 12, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-cl-4-vvh', trainId: 'tr-cl-4', stationId: 'st-vvh', stopNumber: 8, arrivalTime: '11:05', departureTime: '11:06', distanceFromOrigin: 14, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-cl-4-cla', trainId: 'tr-cl-4', stationId: 'st-cla', stopNumber: 9, arrivalTime: '11:08', departureTime: '11:09', distanceFromOrigin: 16, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-cl-4-sin', trainId: 'tr-cl-4', stationId: 'st-sin', stopNumber: 10, arrivalTime: '11:11', departureTime: '11:12', distanceFromOrigin: 18, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-cl-4-mtn', trainId: 'tr-cl-4', stationId: 'st-mtn', stopNumber: 11, arrivalTime: '11:14', departureTime: '11:15', distanceFromOrigin: 20, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-cl-4-dr', trainId: 'tr-cl-4', stationId: 'st-dr', stopNumber: 12, arrivalTime: '11:17', departureTime: '11:18', distanceFromOrigin: 22, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-cl-4-pr', trainId: 'tr-cl-4', stationId: 'st-pr', stopNumber: 13, arrivalTime: '11:20', departureTime: '11:21', distanceFromOrigin: 24, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-cl-4-crd', trainId: 'tr-cl-4', stationId: 'st-crd', stopNumber: 14, arrivalTime: '11:23', departureTime: '11:24', distanceFromOrigin: 26, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-cl-4-chg', trainId: 'tr-cl-4', stationId: 'st-chg', stopNumber: 15, arrivalTime: '11:26', departureTime: '11:27', distanceFromOrigin: 28, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-cl-4-by', trainId: 'tr-cl-4', stationId: 'st-by', stopNumber: 16, arrivalTime: '11:29', departureTime: '11:30', distanceFromOrigin: 30, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-cl-4-snrd', trainId: 'tr-cl-4', stationId: 'st-snrd', stopNumber: 17, arrivalTime: '11:32', departureTime: '11:33', distanceFromOrigin: 32, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-cl-4-msd', trainId: 'tr-cl-4', stationId: 'st-msd', stopNumber: 18, arrivalTime: '11:35', departureTime: '11:36', distanceFromOrigin: 34, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-cl-4-cstm', trainId: 'tr-cl-4', stationId: 'st-cstm', stopNumber: 19, arrivalTime: '11:39', departureTime: null, distanceFromOrigin: 36, platform: '4', haltMinutes: 0 },
    { id: 'r-tr-hl-1-cstm', trainId: 'tr-hl-1', stationId: 'st-cstm', stopNumber: 1, arrivalTime: null, departureTime: '10:00', distanceFromOrigin: 0, platform: '2', haltMinutes: 0 },
    { id: 'r-tr-hl-1-msd', trainId: 'tr-hl-1', stationId: 'st-msd', stopNumber: 2, arrivalTime: '10:02', departureTime: '10:03', distanceFromOrigin: 2, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-hl-1-snrd', trainId: 'tr-hl-1', stationId: 'st-snrd', stopNumber: 3, arrivalTime: '10:05', departureTime: '10:06', distanceFromOrigin: 4, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-hl-1-dkrd', trainId: 'tr-hl-1', stationId: 'st-dkrd', stopNumber: 4, arrivalTime: '10:08', departureTime: '10:09', distanceFromOrigin: 6, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-hl-1-rrd', trainId: 'tr-hl-1', stationId: 'st-rrd', stopNumber: 5, arrivalTime: '10:11', departureTime: '10:12', distanceFromOrigin: 8, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-hl-1-ctgn', trainId: 'tr-hl-1', stationId: 'st-ctgn', stopNumber: 6, arrivalTime: '10:14', departureTime: '10:15', distanceFromOrigin: 10, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-hl-1-sve', trainId: 'tr-hl-1', stationId: 'st-sve', stopNumber: 7, arrivalTime: '10:17', departureTime: '10:18', distanceFromOrigin: 12, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-hl-1-vdlr', trainId: 'tr-hl-1', stationId: 'st-vdlr', stopNumber: 8, arrivalTime: '10:20', departureTime: '10:21', distanceFromOrigin: 14, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-hl-1-gtbn', trainId: 'tr-hl-1', stationId: 'st-gtbn', stopNumber: 9, arrivalTime: '10:23', departureTime: '10:24', distanceFromOrigin: 16, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-hl-1-chf', trainId: 'tr-hl-1', stationId: 'st-chf', stopNumber: 10, arrivalTime: '10:26', departureTime: '10:27', distanceFromOrigin: 18, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-hl-1-cla', trainId: 'tr-hl-1', stationId: 'st-cla', stopNumber: 11, arrivalTime: '10:29', departureTime: '10:30', distanceFromOrigin: 20, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-hl-1-tkng', trainId: 'tr-hl-1', stationId: 'st-tkng', stopNumber: 12, arrivalTime: '10:32', departureTime: '10:33', distanceFromOrigin: 22, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-hl-1-cmbr', trainId: 'tr-hl-1', stationId: 'st-cmbr', stopNumber: 13, arrivalTime: '10:35', departureTime: '10:36', distanceFromOrigin: 24, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-hl-1-gv', trainId: 'tr-hl-1', stationId: 'st-gv', stopNumber: 14, arrivalTime: '10:38', departureTime: '10:39', distanceFromOrigin: 26, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-hl-1-mnkd', trainId: 'tr-hl-1', stationId: 'st-mnkd', stopNumber: 15, arrivalTime: '10:41', departureTime: '10:42', distanceFromOrigin: 28, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-hl-1-vsh', trainId: 'tr-hl-1', stationId: 'st-vsh', stopNumber: 16, arrivalTime: '10:44', departureTime: '10:45', distanceFromOrigin: 30, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-hl-1-sncr', trainId: 'tr-hl-1', stationId: 'st-sncr', stopNumber: 17, arrivalTime: '10:47', departureTime: '10:48', distanceFromOrigin: 32, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-hl-1-jnj', trainId: 'tr-hl-1', stationId: 'st-jnj', stopNumber: 18, arrivalTime: '10:50', departureTime: '10:51', distanceFromOrigin: 34, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-hl-1-neu', trainId: 'tr-hl-1', stationId: 'st-neu', stopNumber: 19, arrivalTime: '10:53', departureTime: '10:54', distanceFromOrigin: 36, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-hl-1-swdv', trainId: 'tr-hl-1', stationId: 'st-swdv', stopNumber: 20, arrivalTime: '10:56', departureTime: '10:57', distanceFromOrigin: 38, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-hl-1-khag', trainId: 'tr-hl-1', stationId: 'st-khag', stopNumber: 21, arrivalTime: '10:59', departureTime: '11:00', distanceFromOrigin: 40, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-hl-1-manr', trainId: 'tr-hl-1', stationId: 'st-manr', stopNumber: 22, arrivalTime: '11:02', departureTime: '11:03', distanceFromOrigin: 42, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-hl-1-knds', trainId: 'tr-hl-1', stationId: 'st-knds', stopNumber: 23, arrivalTime: '11:05', departureTime: '11:06', distanceFromOrigin: 44, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-hl-1-pnvl', trainId: 'tr-hl-1', stationId: 'st-pnvl', stopNumber: 24, arrivalTime: '11:09', departureTime: null, distanceFromOrigin: 46, platform: '1', haltMinutes: 0 },
    { id: 'r-tr-hl-2-pnvl', trainId: 'tr-hl-2', stationId: 'st-pnvl', stopNumber: 1, arrivalTime: null, departureTime: '11:30', distanceFromOrigin: 0, platform: '2', haltMinutes: 0 },
    { id: 'r-tr-hl-2-knds', trainId: 'tr-hl-2', stationId: 'st-knds', stopNumber: 2, arrivalTime: '11:32', departureTime: '11:33', distanceFromOrigin: 2, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-hl-2-manr', trainId: 'tr-hl-2', stationId: 'st-manr', stopNumber: 3, arrivalTime: '11:35', departureTime: '11:36', distanceFromOrigin: 4, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-hl-2-khag', trainId: 'tr-hl-2', stationId: 'st-khag', stopNumber: 4, arrivalTime: '11:38', departureTime: '11:39', distanceFromOrigin: 6, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-hl-2-swdv', trainId: 'tr-hl-2', stationId: 'st-swdv', stopNumber: 5, arrivalTime: '11:41', departureTime: '11:42', distanceFromOrigin: 8, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-hl-2-neu', trainId: 'tr-hl-2', stationId: 'st-neu', stopNumber: 6, arrivalTime: '11:44', departureTime: '11:45', distanceFromOrigin: 10, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-hl-2-jnj', trainId: 'tr-hl-2', stationId: 'st-jnj', stopNumber: 7, arrivalTime: '11:47', departureTime: '11:48', distanceFromOrigin: 12, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-hl-2-sncr', trainId: 'tr-hl-2', stationId: 'st-sncr', stopNumber: 8, arrivalTime: '11:50', departureTime: '11:51', distanceFromOrigin: 14, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-hl-2-vsh', trainId: 'tr-hl-2', stationId: 'st-vsh', stopNumber: 9, arrivalTime: '11:53', departureTime: '11:54', distanceFromOrigin: 16, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-hl-2-mnkd', trainId: 'tr-hl-2', stationId: 'st-mnkd', stopNumber: 10, arrivalTime: '11:56', departureTime: '11:57', distanceFromOrigin: 18, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-hl-2-gv', trainId: 'tr-hl-2', stationId: 'st-gv', stopNumber: 11, arrivalTime: '11:59', departureTime: '12:00', distanceFromOrigin: 20, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-hl-2-cmbr', trainId: 'tr-hl-2', stationId: 'st-cmbr', stopNumber: 12, arrivalTime: '12:02', departureTime: '12:03', distanceFromOrigin: 22, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-hl-2-tkng', trainId: 'tr-hl-2', stationId: 'st-tkng', stopNumber: 13, arrivalTime: '12:05', departureTime: '12:06', distanceFromOrigin: 24, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-hl-2-cla', trainId: 'tr-hl-2', stationId: 'st-cla', stopNumber: 14, arrivalTime: '12:08', departureTime: '12:09', distanceFromOrigin: 26, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-hl-2-chf', trainId: 'tr-hl-2', stationId: 'st-chf', stopNumber: 15, arrivalTime: '12:11', departureTime: '12:12', distanceFromOrigin: 28, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-hl-2-gtbn', trainId: 'tr-hl-2', stationId: 'st-gtbn', stopNumber: 16, arrivalTime: '12:14', departureTime: '12:15', distanceFromOrigin: 30, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-hl-2-vdlr', trainId: 'tr-hl-2', stationId: 'st-vdlr', stopNumber: 17, arrivalTime: '12:17', departureTime: '12:18', distanceFromOrigin: 32, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-hl-2-sve', trainId: 'tr-hl-2', stationId: 'st-sve', stopNumber: 18, arrivalTime: '12:20', departureTime: '12:21', distanceFromOrigin: 34, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-hl-2-ctgn', trainId: 'tr-hl-2', stationId: 'st-ctgn', stopNumber: 19, arrivalTime: '12:23', departureTime: '12:24', distanceFromOrigin: 36, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-hl-2-rrd', trainId: 'tr-hl-2', stationId: 'st-rrd', stopNumber: 20, arrivalTime: '12:26', departureTime: '12:27', distanceFromOrigin: 38, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-hl-2-dkrd', trainId: 'tr-hl-2', stationId: 'st-dkrd', stopNumber: 21, arrivalTime: '12:29', departureTime: '12:30', distanceFromOrigin: 40, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-hl-2-snrd', trainId: 'tr-hl-2', stationId: 'st-snrd', stopNumber: 22, arrivalTime: '12:32', departureTime: '12:33', distanceFromOrigin: 42, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-hl-2-msd', trainId: 'tr-hl-2', stationId: 'st-msd', stopNumber: 23, arrivalTime: '12:35', departureTime: '12:36', distanceFromOrigin: 44, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-hl-2-cstm', trainId: 'tr-hl-2', stationId: 'st-cstm', stopNumber: 24, arrivalTime: '12:39', departureTime: null, distanceFromOrigin: 46, platform: '1', haltMinutes: 0 },
    { id: 'r-tr-hl-3-cstm', trainId: 'tr-hl-3', stationId: 'st-cstm', stopNumber: 1, arrivalTime: null, departureTime: '10:15', distanceFromOrigin: 0, platform: '2', haltMinutes: 0 },
    { id: 'r-tr-hl-3-msd', trainId: 'tr-hl-3', stationId: 'st-msd', stopNumber: 2, arrivalTime: '10:17', departureTime: '10:18', distanceFromOrigin: 2, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-hl-3-snrd', trainId: 'tr-hl-3', stationId: 'st-snrd', stopNumber: 3, arrivalTime: '10:20', departureTime: '10:21', distanceFromOrigin: 4, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-hl-3-dkrd', trainId: 'tr-hl-3', stationId: 'st-dkrd', stopNumber: 4, arrivalTime: '10:23', departureTime: '10:24', distanceFromOrigin: 6, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-hl-3-rrd', trainId: 'tr-hl-3', stationId: 'st-rrd', stopNumber: 5, arrivalTime: '10:26', departureTime: '10:27', distanceFromOrigin: 8, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-hl-3-ctgn', trainId: 'tr-hl-3', stationId: 'st-ctgn', stopNumber: 6, arrivalTime: '10:29', departureTime: '10:30', distanceFromOrigin: 10, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-hl-3-sve', trainId: 'tr-hl-3', stationId: 'st-sve', stopNumber: 7, arrivalTime: '10:32', departureTime: '10:33', distanceFromOrigin: 12, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-hl-3-vdlr', trainId: 'tr-hl-3', stationId: 'st-vdlr', stopNumber: 8, arrivalTime: '10:35', departureTime: '10:36', distanceFromOrigin: 14, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-hl-3-gtbn', trainId: 'tr-hl-3', stationId: 'st-gtbn', stopNumber: 9, arrivalTime: '10:38', departureTime: '10:39', distanceFromOrigin: 16, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-hl-3-chf', trainId: 'tr-hl-3', stationId: 'st-chf', stopNumber: 10, arrivalTime: '10:41', departureTime: '10:42', distanceFromOrigin: 18, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-hl-3-cla', trainId: 'tr-hl-3', stationId: 'st-cla', stopNumber: 11, arrivalTime: '10:44', departureTime: '10:45', distanceFromOrigin: 20, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-hl-3-tkng', trainId: 'tr-hl-3', stationId: 'st-tkng', stopNumber: 12, arrivalTime: '10:47', departureTime: '10:48', distanceFromOrigin: 22, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-hl-3-cmbr', trainId: 'tr-hl-3', stationId: 'st-cmbr', stopNumber: 13, arrivalTime: '10:50', departureTime: '10:51', distanceFromOrigin: 24, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-hl-3-gv', trainId: 'tr-hl-3', stationId: 'st-gv', stopNumber: 14, arrivalTime: '10:53', departureTime: '10:54', distanceFromOrigin: 26, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-hl-3-mnkd', trainId: 'tr-hl-3', stationId: 'st-mnkd', stopNumber: 15, arrivalTime: '10:56', departureTime: '10:57', distanceFromOrigin: 28, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-hl-3-vsh', trainId: 'tr-hl-3', stationId: 'st-vsh', stopNumber: 16, arrivalTime: '11:00', departureTime: null, distanceFromOrigin: 30, platform: '1', haltMinutes: 0 },
    { id: 'r-tr-hl-4-vsh', trainId: 'tr-hl-4', stationId: 'st-vsh', stopNumber: 1, arrivalTime: null, departureTime: '11:15', distanceFromOrigin: 0, platform: '2', haltMinutes: 0 },
    { id: 'r-tr-hl-4-mnkd', trainId: 'tr-hl-4', stationId: 'st-mnkd', stopNumber: 2, arrivalTime: '11:17', departureTime: '11:18', distanceFromOrigin: 2, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-hl-4-gv', trainId: 'tr-hl-4', stationId: 'st-gv', stopNumber: 3, arrivalTime: '11:20', departureTime: '11:21', distanceFromOrigin: 4, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-hl-4-cmbr', trainId: 'tr-hl-4', stationId: 'st-cmbr', stopNumber: 4, arrivalTime: '11:23', departureTime: '11:24', distanceFromOrigin: 6, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-hl-4-tkng', trainId: 'tr-hl-4', stationId: 'st-tkng', stopNumber: 5, arrivalTime: '11:26', departureTime: '11:27', distanceFromOrigin: 8, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-hl-4-cla', trainId: 'tr-hl-4', stationId: 'st-cla', stopNumber: 6, arrivalTime: '11:29', departureTime: '11:30', distanceFromOrigin: 10, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-hl-4-chf', trainId: 'tr-hl-4', stationId: 'st-chf', stopNumber: 7, arrivalTime: '11:32', departureTime: '11:33', distanceFromOrigin: 12, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-hl-4-gtbn', trainId: 'tr-hl-4', stationId: 'st-gtbn', stopNumber: 8, arrivalTime: '11:35', departureTime: '11:36', distanceFromOrigin: 14, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-hl-4-vdlr', trainId: 'tr-hl-4', stationId: 'st-vdlr', stopNumber: 9, arrivalTime: '11:38', departureTime: '11:39', distanceFromOrigin: 16, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-hl-4-sve', trainId: 'tr-hl-4', stationId: 'st-sve', stopNumber: 10, arrivalTime: '11:41', departureTime: '11:42', distanceFromOrigin: 18, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-hl-4-ctgn', trainId: 'tr-hl-4', stationId: 'st-ctgn', stopNumber: 11, arrivalTime: '11:44', departureTime: '11:45', distanceFromOrigin: 20, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-hl-4-rrd', trainId: 'tr-hl-4', stationId: 'st-rrd', stopNumber: 12, arrivalTime: '11:47', departureTime: '11:48', distanceFromOrigin: 22, platform: '1', haltMinutes: 1 },
    { id: 'r-tr-hl-4-dkrd', trainId: 'tr-hl-4', stationId: 'st-dkrd', stopNumber: 13, arrivalTime: '11:50', departureTime: '11:51', distanceFromOrigin: 24, platform: '2', haltMinutes: 1 },
    { id: 'r-tr-hl-4-snrd', trainId: 'tr-hl-4', stationId: 'st-snrd', stopNumber: 14, arrivalTime: '11:53', departureTime: '11:54', distanceFromOrigin: 26, platform: '3', haltMinutes: 1 },
    { id: 'r-tr-hl-4-msd', trainId: 'tr-hl-4', stationId: 'st-msd', stopNumber: 15, arrivalTime: '11:56', departureTime: '11:57', distanceFromOrigin: 28, platform: '4', haltMinutes: 1 },
    { id: 'r-tr-hl-4-cstm', trainId: 'tr-hl-4', stationId: 'st-cstm', stopNumber: 16, arrivalTime: '12:00', departureTime: null, distanceFromOrigin: 30, platform: '1', haltMinutes: 0 },
  ];
  await prisma.trainRoute.createMany({ data: routes });
  console.log('[SUCCESS] Train Routes seeded');

  // --- FOOD VENDORS --------------------------------------------------------
  const vendors = [
    { id: 'v-1', stationId: 'st-ndls', name: 'Delhi Darbar', cuisine: 'North Indian', rating: 4.5, isOpen: true },
    { id: 'v-2', stationId: 'st-cstm', name: 'Aram Vada Pav', cuisine: 'Street Food', rating: 4.8, isOpen: true },
    { id: 'v-3', stationId: 'st-adi',  name: 'Gujarati Thali House', cuisine: 'Gujarati', rating: 4.3, isOpen: true },
    { id: 'v-4', stationId: 'st-dr',   name: 'Prakash Upahar Kendra', cuisine: 'Maharashtrian', rating: 4.7, isOpen: true },
  ];
  await prisma.foodVendor.createMany({ data: vendors });

  const foodItems = [
    { id: 'fi-1', vendorId: 'v-1', name: 'Butter Chicken Meal', category: 'Lunch', price: 250, isVeg: false, isAvailable: true, description: 'Served with 2 Naan and Rice' },
    { id: 'fi-2', vendorId: 'v-1', name: 'Paneer Tikka', category: 'Snacks', price: 150, isVeg: true, isAvailable: true, description: 'With mint chutney' },
    { id: 'fi-3', vendorId: 'v-2', name: 'Jumbo Vada Pav', category: 'Snacks', price: 40, isVeg: true, isAvailable: true, description: 'Iconic Mumbai snack' },
    { id: 'fi-4', vendorId: 'v-3', name: 'Dhokla Set', category: 'Breakfast', price: 80, isVeg: true, isAvailable: true, description: 'Spongy and fresh' },
    { id: 'fi-5', vendorId: 'v-4', name: 'Misal Pav', category: 'Breakfast', price: 90, isVeg: true, isAvailable: true, description: 'Spicy and authentic' },
  ];
  await prisma.foodItem.createMany({ data: foodItems });
  console.log('[SUCCESS] Food Ecosystem seeded');

  // --- DELAYS --------------------------------------------------------------
  const todayDate = new Date();
  const delaysData: any[] = [];
  
  const trainIds = [ 'tr-12951', 'tr-12009', 'tr-12263', 'tr-12627', 'tr-12859', 'tr-dq', 'tr-dq-ret', 'tr-kk', 'tr-kk-ret', 'tr-wl-1', 'tr-wl-2', 'tr-wl-3', 'tr-wl-4', 'tr-wl-5', 'tr-cl-1', 'tr-cl-2', 'tr-cl-3', 'tr-cl-4', 'tr-hl-1', 'tr-hl-2', 'tr-hl-3', 'tr-hl-4' ];

  const delayReasons = [
    'Signal Failure', 'Track maintenance', 'Weather conditions',
    'Platform congestion', 'Late arrival of rake', 'Engine trouble'
  ];

  for (let i = 0; i <= 30; i++) {
    const d = new Date();
    d.setDate(todayDate.getDate() - i);
    const dateStr = d.toISOString().split('T')[0];

    trainIds.forEach((trainId) => {
      const isPriority = trainId.startsWith('tr-12') || trainId === 'tr-dq' || trainId === 'tr-dq-ret';
      const delayProb = isPriority ? 0.15 : 0.40;

      if (Math.random() < delayProb) {
        const delayMins = Math.floor(Math.random() * (isPriority ? 20 : 60)) + 5;
        const reason = delayReasons[Math.floor(Math.random() * delayReasons.length)];
        delaysData.push({
          id: `d-${trainId}-${dateStr}`,
          trainId,
          date: dateStr,
          delayMinutes: delayMins,
          reason,
        });
      } else {
        delaysData.push({
          id: `d-${trainId}-${dateStr}`,
          trainId,
          date: dateStr,
          delayMinutes: 0,
          reason: null,
        });
      }
    });
  }

  await prisma.delay.createMany({ data: delaysData });
  console.log(`[SUCCESS] ${delaysData.length} Delay records seeded (past 30 days included)`);

  console.log('[SUCCESS] Seeding Completed Successfully!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
